# PID调试参数配置文件
# 使用方法: rosparam load this_file.yaml 或在launch文件中加载

# 调试模式设置
# 1 = 只调试加速度环 (内环)
# 2 = 调试速度环+加速度环 (中环+内环)  
# 3 = 全三环级联调试
debug_mode: 3

# 目标深度(米)
target_altitude: 0.6
# # 位置环PID参数
# position_pid:
#   kp: 20.0
#   ki: 0.05
#   kd: 0.0

# # 速度环PID参数  
# velocity_pid:
#   kp: 10.0
#   ki: 0.05
#   kd: 0.0

# # 加速度环PID参数 (建议从这个环开始调试)
# acceleration_pid:
#   kp: 0.18
#   ki: 0.03
#   kd: 0.9

# # 手动设定点 (用于单环或双环调试)
# # 注意：在全三环模式(debug_mode: 3)下应该设置enable: false
# manual_setpoints:
#   enable: false          # 全三环模式下应设为false
#   velocity: 0.13         # 速度设定点 (m/s)
#   acceleration: 1.0      # 加速度设定点 (m/s²)
# 位置环PID参数
position_pid:
  kp: 5.0
  ki: 0.0
  kd: 0.5

# 速度环PID参数  
velocity_pid:
  kp: 15
  ki: 0.0
  kd: 0.5

# 加速度环PID参数 (建议从这个环开始调试)
acceleration_pid:
  kp: 5
  ki: 0.03
  kd: 0.5

# 手动设定点 (用于单环或双环调试)
# 注意：在全三环模式(debug_mode: 3)下应该设置enable: false
manual_setpoints:
  enable: true          # 全三环模式下应设为false
  velocity: 0.13         # 速度设定点 (m/s)
  acceleration: 0.2      # 加速度设定点 (m/s²)

# 调试输出设置
verbose_debug: true

# ============ 新增：PWM控制参数 ============
# PWM平滑控制参数（解决PWM跟不上PID计算的问题）
pwm_base_change_rate: 3.0    # 基础PWM变化速率（小误差时）
pwm_max_change_rate: 15.0    # 最大PWM变化速率（大误差时）
pwm_tolerance: 3             # PWM到位判断容差
pid_calculation_interval: 5   # PID计算间隔（控制周期数）


# ====== 调试建议和注意事项 ======

# 1. PWM参数调整建议：
#    - 如果PWM调整太慢，增大 pwm_base_change_rate 和 pwm_max_change_rate
#    - 如果系统振荡，减小变化速率或增大 pid_calculation_interval
#    - pwm_tolerance 建议保持在 2-5 之间

# 2. PID调试顺序：
#    第一阶段：加速度环
#    - 先调 kp：从0.1开始逐渐增大，直到响应足够快但不振荡
#    - 再调 kd：消除超调和振荡
#    - 最后调 ki：消除静差（小心积分饱和）
#    
#    第二阶段：速度环
#    - 加速度环调好后，开始调速度环kp
#    - 给定小的速度指令，观察跟踪效果
#    
#    第三阶段：位置环  
#    - 速度环调好后，最后调位置环
#    - 从小的kp开始，避免过冲

# 3. 常见问题和解决方法：
#    - 如果系统响应慢：增大对应环的kp
#    - 如果有振荡：减小kp或增大kd
#    - 如果有超调：增大kd或减小kp
#    - 如果有静差：适当增加ki，但要防止积分饱和
#    - 如果PWM跳跃：检查pwm_change_rate设置

# 4. 安全建议：
#    - 调试时建议target_altitude设小一点（0.3-0.5米）
#    - 随时准备切换到手动模式
#    - 观察电机温度，避免长时间高功率运行