# ROV Dock跟踪 PID参数配置文件
# 使用方法: rosparam load this_file.yaml

# ============ 控制模式设置 ============
# 控制模式：
# 1 = 仅深度控制
# 2 = 仅视觉Yaw控制 (无dock时搜寻，有dock时调整)
# 3 = Dock跟踪模式（定深→搜寻→Yaw调整→前进跟踪）
control_mode: 3

# 深度控制调试模式：
# 1 = 只调试加速度环（内环）
# 2 = 调试速度环+加速度环（中环+内环）  
# 3 = 全三环级联调试
debug_mode: 3

# ============ 目标设定 ============
# 目标深度（米）
target_altitude: 0.5

# 前进推力（用于Dock跟踪模式的前进阶段）
forward_thrust: 30.0

# 搜寻转圈速度（用于搜寻dock）
search_turn_speed: -40.0

# ============ 状态机参数 ============
# 定深稳定所需时间（秒）
depth_stable_time: 3.0

# 搜寻持续时间（秒，超时后重新开始搜寻）
search_time: 15.0

# 深度稳定容忍度（米）
depth_tolerance: 0.1

# Yaw调整容忍度（像素，dock居中的判断标准）
yaw_adjustment_tolerance: 20.0

# ============ 深度控制PID参数 ============
# 位置环PID参数（深度外环）
position_pid:
  kp: 15.0
  ki: 0.0
  kd: 0.0

# 速度环PID参数（深度中环）
velocity_pid:
  kp: 15.0
  ki: 0.0
  kd: 0.0

# 加速度环PID参数（深度内环）
acceleration_pid:
  kp: 2.0
  ki: 0.1
  kd: 0.8

# ============ 视觉Yaw控制PID参数 ============
# 基于像素误差的Yaw控制
visual_yaw_pid:
  kp: 0.015
  # ki: 0.05
  # kd: 0.8
  ki: 0.05
  kd: 0.08

# ============ 手动设定点（用于PID调试）============
manual_setpoints:
  enable: true
  velocity: 0.13        # 速度设定点 (m/s)
  acceleration: 1.0     # 加速度设定点 (m/s²)

# ============ 相机参数 ============
camera_cx: 318.509118
camera_cy: 247.737583
camera_fx: 410.971988
camera_fy: 412.393625

# ============ 控制参数 ============
# 控制死区
altitude_deadzone: 0.02       # 深度死区（米）
visual_yaw_deadzone: 10.0     # 视觉Yaw死区（像素）

# PWM控制
base_throttle: 1500
pwm_deadzone: 30
pwm_base_change_rate: 3.0
pwm_max_change_rate: 15.0
pid_calculation_interval: 5

# ============ 调试输出 ============
verbose_debug: true

# ============ 实时调整命令参考 ============
# 控制模式:
#   rosparam set /control_mode 2    # 切换到仅视觉Yaw控制
#   rosparam set /control_mode 3    # 切换到Dock跟踪模式
# 
# 深度控制:
#   rosparam set /position_pid/kp 20.0
#   rosparam set /acceleration_pid/ki 0.05
# 
# 视觉控制:
#   rosparam set /visual_yaw_pid/kp 0.006
#   rosparam set /search_turn_speed 80.0
#
# 运动控制:
#   rosparam set /forward_thrust 50.0
#   rosparam set /target_altitude 0.6
#
# 状态机参数:
#   rosparam set /depth_stable_time 5.0
#   rosparam set /search_time 20.0
#   rosparam set /yaw_adjustment_tolerance 15.0
#
# 调试模式:
#   rosparam set /debug_mode 1      # 仅调试加速度环

# ============ 控制逻辑说明 ============
# 
# 仅视觉Yaw控制模式 (control_mode: 2):
#   - 无dock检测: 原地转圈搜寻 (search_turn_speed)
#   - 检测到dock: 调整Yaw角使dock居中
#
# Dock跟踪模式状态机 (control_mode: 3):
#   1. 定深阶段: 只执行深度控制，稳定到目标深度
#   2. 搜寻阶段: 保持深度 + 原地转圈搜寻dock
#   3. Yaw调整阶段: 保持深度 + 调整Yaw使dock居中
#   4. 前进跟踪阶段: 保持深度 + 前进 + 持续Yaw跟踪
#
# 电机布局:
#   CH1: 右推进器（前进+Yaw控制）
#   CH2: 左推进器（前进+Yaw控制）  
#   CH3: 上推进器（深度控制）
#   CH4: 下推进器（深度控制）